-- Create registration request table
CREATE TABLE T_REGISTRATION_REQUEST (
  RRE_ID_C VARCHAR(36) NOT NULL,
  RRE_USERNAME_C VARCHAR(50) NOT NULL,
  RRE_EMAIL_C VARCHAR(100) NOT NULL,
  RRE_PASSWORD_C VARCHAR(100) NOT NULL,
  RRE_STATUS_C VARCHAR(20) NOT NULL,
  RRE_CREATEDATE_D TIMESTAMP NOT NULL,
  RRE_UPDATEDATE_D TIMESTAMP,
  RRE_ADMIN_ID_C VARCHAR(36),
  RRE_REJECTION_REASON_C VARCHAR(500),
  PRIMARY KEY (RRE_ID_C)
);

-- Add index on username
CREATE INDEX IDX_RRE_USERNAME ON T_REGISTRATION_REQUEST(RRE_USERNAME_C);

-- Add index on status
CREATE INDEX IDX_RRE_STATUS ON T_REGISTRATION_REQUEST(RRE_STATUS_C);

-- Update database version
UPDATE T_CONFIG SET CFG_VALUE_C = '11' WHERE CFG_ID_C = 'DB_VERSION'; 